export const NOT_FOUND = 'GENERIC.NOT_FOUND';
export const INTERNAL_SERVER_ERROR = 'GENERIC.INTERNAL_SERVER_ERROR';

export const USER_NOT_FOUND = 'USER.NOT_FOUND';
export const USER_ALREADY_EXIST = 'USER.ALREALY_EXIST';
