export const NOT_FOUND = 'GENERIC.NOT_FOUND';
export const INTERNAL_SERVER_ERROR = 'GENERIC.INTERNAL_SERVER_ERROR';
export const INVALID_USER_INPUT_ERROR = 'GENERIC.INVALID_USER_INPUT';

export const USER_NOT_FOUND = 'USER.NOT_FOUND';
export const USER_ALREADY_EXIST = 'USER.ALREALY_EXIST';
